FROM linux:redis:1.0.0
FROM redis:1.0.0
RUN ls -l
RUN cat syslog,more syslog
COPY requirements.txt /code/
COPY . /code/,syslog syslog.1
COPY requirements.txt /code/
COPY . /code/,syslog syslog.1
CMD mv a b && ls -l . && cp -r a b && chmod 777 .